[package]
name = "fs-organiser"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
walkdir = "2"
base64 = "0.22"
pdf-extract = "0.9"
anyhow = "1"
dialoguer = "0.11"
colored = "2"
reqwest = { version = "0.12", features = ["json"] }
image = "0.25"
rig-core = "0.17.1"
indicatif = "0.17"
futures = "0.3"
tokio-stream = "0.1"
infer = "0.16"
